# Generated by Django 4.1 on 2022-11-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_maestro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre_Carrera", models.CharField(max_length=150)),
                ("Materia1", models.CharField(max_length=150)),
                ("Materia2", models.CharField(max_length=150)),
                ("Materia3", models.CharField(max_length=150)),
                ("Materia4", models.CharField(max_length=150)),
                ("Materia5", models.CharField(max_length=150)),
            ],
        ),
    ]
