# Generated by Django 4.1 on 2022-11-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_carrera"),
    ]

    operations = [
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=150)),
                ("ApellidoP", models.CharField(max_length=150)),
                ("ApellidoM", models.CharField(max_length=150)),
                ("Nombre_Carrera", models.CharField(max_length=150)),
                ("Materia1H", models.CharField(max_length=150)),
                ("Materia2H", models.CharField(max_length=150)),
                ("Materia3H", models.CharField(max_length=150)),
                ("Materia4H", models.CharField(max_length=150)),
                ("Materia5H", models.CharField(max_length=150)),
            ],
        ),
    ]
